# Install hooks with:           pre-commit install --hook-type pre-commit --hook-type pre-push
# Run on all files:              pre-commit run --all-files
# Keep hook versions fresh:     pre-commit autoupdate

repos:
  - repo: local
    hooks:
      - id: core
        name: format and lint core
        language: system
        entry: make format lint
        files: ^src/
        pass_filenames: false